name: ${project.name}
version: ${project.version}
description: ${description}
author: CodeItForYou
main: ${package}
softdepend: [WorldEdit]

permissions:
  portals.command.BPortals:
    description: Allowed to access the command /BPortals.
    default: op
  portals.portal.*:
    description: Access to all portals.
    default: true