name: ${project.name}
version: ${project.version}
description: ${description}
author: YoFuzzy3
main: ${package}
softdepend: [WorldEdit]

commands:
  portals:
    description: Do cool stuff.
permissions:
  portals.command.BPortals:
    description: Allowed to access the command /BPortals.
    default: op
  portals.portal.*:
    description: Access to all portals.
    default: true